replicaCount: 1

image:
  repository: smartcolumbusos/push_gateway
  tag: development
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 5555
  type: NodePort

assignedDatasetId: "a-dataset-uuid"

kafka:
  brokers: streaming-service-kafka-bootstrap.streaming-prime:9092

redis:
  host: redis.external-services

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
