apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-gateway-{{ .Values.location }}
  labels:
{{ include "push-gateway.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: push-gateway-{{ .Values.location }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: push-gateway-{{ .Values.location }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: push-port
              containerPort: {{ .Values.service.port }}
              protocol: UDP
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: KAFKA_BROKERS
              value: {{ .Values.kafka.brokers }}
            - name: LISTEN_PORT
              value: {{ quote .Values.service.port }}
            - name: ASSIGNED_DATASET_ID
              value: {{ .Values.assignedDatasetId }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
