apiVersion: v1
kind: Service
metadata:
  name: push-gateway
  labels:
{{ include "push-gateway.labels" . | indent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    {{- if .Values.service.internal }}
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    {{- end }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      protocol: UDP
      name: push-port
  selector:
    app.kubernetes.io/name: push-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
