apiVersion: v1
kind: Service
metadata:
  name: push-gateway
  labels:
{{ include "push-gateway.labels" . | indent 4 }}
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: {{ .Values.service.port }}
      protocol: UDP
      name: push-port
  selector:
    app.kubernetes.io/name: push-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
